# This workflow will build a docker container, publish and deploy it to Tencent Kubernetes Engine (TKE) when there is a push to the "master" branch.
#
# To configure this workflow:
#
# 1. Ensure that your repository contains the necessary configuration for your Tencent Kubernetes Engine cluster,
#    including deployment.yml, kustomization.yml, service.yml, etc.
#
# 2. Set up secrets in your workspace:
#    - TENCENT_CLOUD_SECRET_ID with Tencent Cloud secret id
#    - TENCENT_CLOUD_SECRET_KEY with Tencent Cloud secret key
#    - TENCENT_CLOUD_ACCOUNT_ID with Tencent Cloud account id
#    - TKE_REGISTRY_PASSWORD with TKE registry password
#
# 3. Change the values for the TKE_IMAGE_URL, TKE_REGION, TKE_CLUSTER_ID and DEPLOYMENT_NAME environment variables (below).

name: Tencent Kubernetes Engine

on:
  push:
    branches: [ "master" ]

# Environment variables available to all jobs and steps in this workflow
env:
  TKE_IMAGE_URL: ccr.ccs.tencentyun.com/demo/mywebapp
  TKE_REGION: ap-guangzhou
  TKE_CLUSTER_ID: cls-mywebapp
  DEPLOYMENT_NAME: tke-test

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: dev
    steps:

    - name: build
      uses: actions/checkout@v3

  deploy-dev:
    name: Deploy-DEV
    runs-on: ubuntu-latest
    environment: dev
    needs: build
    steps:
    - name: dev-1
      uses: actions/checkout@v3

  deploy-dev-2:
    name: Deploy-DEV-2
    runs-on: ubuntu-latest
    environment: dev
    needs: build
    steps:
    - name: dev-2
      uses: actions/checkout@v3

  test-dev:
    name: Test-DEV
    runs-on: ubuntu-latest
    environment: dev
    needs: deploy-dev
    steps:

    - name: dev-1
      uses: actions/checkout@v3

  test-dev-2:
    name: Test-DEV-2
    runs-on: ubuntu-latest
    environment: dev
    needs: deploy-dev-2
    steps:

    - name: dev-1
      uses: actions/checkout@v3

  release:
    name: Release
    runs-on: ubuntu-latest
    environment: release
    needs: test-dev
    steps:

    - name: release
      uses: actions/checkout@v3
